[package]
name = "skald-wasm"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "WebAssembly bindings for Skald"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
skald = { path = "../skald", default-features = false }
wasm-bindgen = "0.2"
